---
# Bootstrap K8S cluster on macbook M1 virtual machines (executes preparation with k8shosts)
- name: Init Kubernetes with kubeadm 
  hosts: k8smasterInit
  vars_files:
    - "{{ passwd_file }}"
    - "{{ modules_list }}"
  tasks:
    - name: Ping host
      ansible.builtin.ping:

# ------------------------------ K8S installation ------------------------------
    - name: Check if Kubernetes was already installed
      stat:
        path: /var/log/kubeadm.out
      register: kubeadm_init

    - name: Upload bash helpers to K8S master
      copy:
        src: helpers
        dest: ~/
        force: true
        mode: "0755"
      when: not kubeadm_init.stat.exists

    - name: Init cluster with parameters
      debug:
        msg: kubeadm init --config=/root/helpers/confkubeadm.yaml
        #msg: kubeadm init --kubernetes-version="{{ kubernetesVersion }}" --pod-network-cidr="{{ pod_network_cidr }}" --service-cidr="{{ service_cidr }}" --apiserver-advertise-address="{{ ansible_default_ipv4.address }}" --service-dns-domain="{{ cluster_domain }}"
      when: not kubeadm_init.stat.exists

    - shell: 
        creates: /var/log/kubeadm.out
        cmd: "kubeadm init --config=/root/helpers/confkubeadm.yaml > /var/log/kubeadm.out 2>&1"
        #cmd: "kubeadm init --kubernetes-version={{ kubernetesVersion }} --pod-network-cidr={{ pod_network_cidr }} --service-cidr={{ service_cidr }} --apiserver-advertise-address={{ ansible_default_ipv4.address }} --service-dns-domain={{ cluster_domain }} > /var/log/kubeadm.out 2>&1"
      when: not kubeadm_init.stat.exists

    - name: Fetch kubeadm output (command and token to join nodes to cluster) to local storage
      fetch:
        src: /var/log/kubeadm.out
        dest: ./ansible/kubeadm_{{ ansible_hostname }}_{{ ansible_date_time.date }}_{{ ansible_date_time.time}}/
        flat: yes
      when: not kubeadm_init.stat.exists

    - name: mkdir kube local folder
      shell:
        creates: ~/.kube/config.yaml
        cmd: "mkdir ~/.kube"
      when: not kubeadm_init.stat.exists

    - name: copy admin.conf to config.yaml
      shell:
        creates: ~/.kube/config.yaml
        cmd: "cp /etc/kubernetes/admin.conf ~/.kube/config.yaml"
      when: not kubeadm_init.stat.exists

    - name: chmod r on config.yaml
      shell:
        cmd: "chmod 600 ~/.kube/config.yaml"
      when: not kubeadm_init.stat.exists

    - name: Check if KUBECONFIG already specified in environment
      shell:
        cmd: "if sh -c 'env | grep KUBECONFIG > /dev/null 2>&1' ; then echo EXIST; else echo NOT EXIST; fi"
      register: kubeconfig_exist

    - lineinfile:
        dest: ~/.bashrc
        line: "export KUBECONFIG=~/.kube/config.yaml"
        state: present
      when: kubeconfig_exist.stdout == "NOT EXIST"

    - debug:
        msg: "Kubernetes was succesfully installed on {{ ansible_hostname }} -------------------"
      when: not kubeadm_init.stat.exists

    - debug:
        msg: "Kubernetes was ALREADY installed on {{ ansible_hostname }} -------------------"
      when: kubeadm_init.stat.exists


# ------------------------------ HELM installation ------------------------------
    - name: Check if HELM already installed in the cluster
      stat:
        path: /usr/local/bin/helm
      register: helm_init

    - debug:
        msg: "------------- HELM ALREADY installed --------------"
      when: helm_init.stat.exists

    - name: timestamp
      shell:
        cmd: "date >> /var/log/helm.out"
      when: not helm_init.stat.exists

    - name: Download HELM binaries
      shell:
        creates: ~/helm-{{ helm_version }}-linux-arm64.tar.gz
        cmd: "curl -fsSLo /root/helm-{{ helm_version }}-linux-arm64.tar.gz https://get.helm.sh/helm-{{ helm_version }}-linux-arm64.tar.gz"
      when: not helm_init.stat.exists

    - name: Install HELM on master
      shell:
        cmd: "cd ~/ && tar -zxvf helm-{{ helm_version }}-linux-arm64.tar.gz && mv linux-arm64/helm /usr/local/bin/helm && helm version --kubeconfig=~/.kube/config.yaml >> /var/log/helm.out 2>&1"
      when: not helm_init.stat.exists

    - name: Check HELM installed
      stat:
        path: /usr/local/bin/helm
      register: helm_complete

    - debug:
        msg: "------------- HELM succesfully installed --------------"
      when: not helm_complete.stat.exists

## ------------------------------ CALICO installation ------------------------------
    - name: Check if CALICO already installed in the cluster
      stat:
        path: /var/log/calico.out
      register: calico_init

    - debug:
        msg: "------------- CALICO ALREADY installed --------------"
      when: calico_init.stat.exists

    - name: timestamp
      shell:
        cmd: "date > /var/log/calico.out"
      when: not calico_init.stat.exists

    - name: Upload calico helm-releases to K8S master
      copy:
        src: helm-releases
        dest: ~/
        force: true
      when: not calico_init.stat.exists

    - name: Add calico helm repositories
      shell:
        cmd: "helm repo add {{ item.name }} {{ item.url }} >> /var/log/calico.out 2>&1"
      loop: "{{ helmRepositories.calico }}"
      when: not calico_init.stat.exists

    - name: Install calico charts
      shell:
        chdir: ~/helm-releases/calico-system
        cmd: /bin/bash -c "~/helpers/helm-deploy.sh ~/.kube/config.yaml calico-system {{ item.name }} --set pod_network_cidr={{ pod_network_cidr }} >> /var/log/calico.out 2>&1"
      loop: "{{ calicoReleases }}"
      when: not calico_init.stat.exists

#    - name: Install calico custom resources in the cluster
#      shell:
#        cmd: "sleep 30 && sed --in-place 's/192.168.0.0\\\/16/{{ pod_network_cidr_calico }}/g' /root/calico-custom-resources.yaml && kubectl create -f /root/calico-custom-resources.yaml --kubeconfig=/root/.kube/config.yaml >> /var/log/calico.out 2>&1"
#      when: (ansible_hostname == master01) and (not calico_init.stat.exists)
#
#    - name: Install CALICOCTL in KUBECTL on master01
#      shell:
#        creates: /usr/local/bin/kubectl-calico
#        cmd: "curl -fsSLo /usr/local/bin/kubectl-calico https://github.com/projectcalico/calico/releases/download/{{ calico_version }}/calicoctl-linux-arm64 && chmod +x /usr/local/bin/kubectl-calico && kubectl calico -h --kubeconfig=/root/.kube/config.yaml >> /var/log/calico.out 2>&1"
#      when: ansible_hostname == master01
#
#    - debug:
#        msg: "----------- CALICO installed. Please wait 2 minutes at least to allow CNI and COREDNS wake up ---------------"
#      when: (ansible_hostname == master01) and (not calico_init.stat.exists)
#
##    - name: Install CANAL in cluster and enable CNI
##      shell:
##        creates: /root/canal.yaml
##        cmd: "curl -fsSLo /root/canal.yaml https://raw.githubusercontent.com/projectcalico/calico/{{ calico_version }}/manifests/canal.yaml && kubectl apply -f /root/canal.yaml --kubeconfig=/root/.kube/config.yaml >> /var/log/calico.out 2>&1"
##      when: ansible_hostname == master01
##
## ------------------------------ master01 specific section -------------------------
## Continue in k8saddones.yaml
#    - debug:
#        msg: "Please generate kubeadm.sh, start k8sworkers.yaml, add nameserver or hosts to coredns and continue with k8saddones.yaml playbook! -------------------"
#      when: ansible_hostname == master01
#
#  roles:
##    - { role: disable-ipv6, tag: disable-ipv6 }
