---
# Join worker nodes to K8S cluster
- name: Init Kubernetes with kubeadm
  hosts: k8sworkers
  vars_files:
    - "{{ passwd_file }}"
    - "{{ modules_list }}"
  tasks:
    - name: Ping host
      ansible.builtin.ping:

    - name: Check if node was already joined to the cluster
      stat:
        path: /var/log/kubeadm.out
      register: kubeadm_init

    - name: Upload helpers to K8S master
      copy:
        src: helpers
        dest: ~/
        force: true
        mode: "0755"
      when: not kubeadm_init.stat.exists

    - name: Join node to the cluster
      shell:
        creates: /var/log/kubeadm.out
        cmd: "/bin/bash -c ~/helpers/kubeadm_join.sh > /var/log/kubeadm.out"
      when: not kubeadm_init.stat.exists
