#
metallb_pool: "10.10.253.200-10.10.253.220"

resources:
  - apiVersion: metallb.io/v1beta1
    kind: IPAddressPool
    metadata:
      name: ip-addresspool
      namespace: metallb-system
    spec:
      addresses:
        - "{{ .Values.metallb_pool }}"
  - apiVersion: metallb.io/v1beta1
    kind: L2Advertisement
    metadata:
      name: l2advertisement
      namespace: metallb-system
    spec:
      ipAddressPools:
      - ip-addresspool
