---
# tasks file for ansible-roles/k8s
- name: Install k8s utilities
  debug:
    msg: "Install k8s utilities: kubectl/kubelet/kubeadm"
  tags: k8s

- name: Google Cloud public signing key
  shell:
    creates: /etc/apt/keyrings/kubernetes-apt-keyring.gpg
    cmd: "curl -fsSL https://pkgs.k8s.io/core:/stable:/v{{ kubernetesToolsVersion }}/deb/Release.key | sudo gpg --dearmor -o /etc/apt/keyrings/kubernetes-apt-keyring.gpg"

- name: Add Kubernetes repository
  shell:
    creates: /etc/apt/sources.list.d/kubernetes.list
    cmd: "echo 'deb [signed-by=/etc/apt/keyrings/kubernetes-apt-keyring.gpg] https://pkgs.k8s.io/core:/stable:/v{{ kubernetesToolsVersion }}/deb/ /' | sudo tee /etc/apt/sources.list.d/kubernetes.list"

- name: apt update
  apt:
    update_cache: true
    force_apt_get: true

- apt:
    name: [ "kubectl", "kubelet", "kubeadm" ]
    state: "present"

- name: Create /etc/containerd
  file:
    path: /etc/containerd
    state: directory
    mode: "755"

- name: Create default containerd config
  shell:
    creates: /etc/containerd/config.toml
    cmd: "containerd config default > /etc/containerd/config.toml"

- name: Enable systemd containerd
  lineinfile:
    path: /etc/containerd/config.toml
    regexp: 'SystemdCgroup \= false'
    line: "{{ ' ' * 12 }}SystemdCgroup = true"

- name: Restart containerd
  systemd:
    name: containerd
    state: restarted


- debug:
    msg: "------------ K8S utilities INSTALLED -------------"
