---
# tasks file for ansible-roles/k8s
- name: Install k8s utilities
  debug:
    msg: "Install k8s utilities: kubectl/kubelet/kubeadm"
  tags: k8s

- name: Google Cloud public signing key
  shell:
    creates: /etc/apt/keyrings/kubernetes-apt-keyring.gpg
    cmd: "curl -fsSL https://pkgs.k8s.io/core:/stable:/v1.30/deb/Release.key | sudo gpg --dearmor -o /etc/apt/keyrings/kubernetes-apt-keyring.gpg"

- name: Add Kubernetes repository
  shell:
    creates: /etc/apt/sources.list.d/kubernetes.list
    cmd: "echo 'deb [signed-by=/etc/apt/keyrings/kubernetes-apt-keyring.gpg] https://pkgs.k8s.io/core:/stable:/v1.30/deb/ /' | sudo tee /etc/apt/sources.list.d/kubernetes.list"

- name: apt update
  apt:
    update_cache: true
    force_apt_get: true

- apt:
    name: [ "kubectl={{ kubernetesVersion }}", "kubelet={{ kubernetesVersion }}", "kubeadm={{ kubernetesVersion }}" ]
    state: "present"

- debug:
    msg: "------------ K8S utilities INSTALLED -------------"
